# -*- coding: utf-8 -*-
"""BrainyBeam Info-Tech Pvt Ltd(Task_1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCTtLUS0bjxaNYND7qQy6vzvLF71WjYT

**Title:Mathematical operations, Description: Solve a system of linear equations using numpy's linear algebra functions.**
"""

import numpy as np

A = np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]])
B = np.array([8, 0, -2])

solution = np.linalg.solve(A, B)

print(solution)